"""
FastAPI application — HDY Monitor backend.

Authentication: single-user JWT.
Credentials and other settings are read from config.json generated by install.sh.
"""
from __future__ import annotations

import json
import logging
import os
import secrets
import shutil
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional

import httpx
from fastapi import Depends, FastAPI, File, HTTPException, Request, UploadFile, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse, PlainTextResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from fastapi.staticfiles import StaticFiles
from jose import JWTError, jwt
from passlib.context import CryptContext

import crawler
import database
import notifier
from models import (
    ChangeLog,
    ClusterProxyRequest,
    ClusterSyncRequest,
    ClusterVerifyAdminRequest,
    ConfigUpdate,
    CrawlerStatus,
    LoginRequest,
    NodeCreate,
    NotifyTestRequest,
    PaginatedChanges,
    PaginatedProducts,
    SiteAccount,
    SiteAccountCreate,
    SiteLoginRequest,
    TokenResponse,
    VisitorLoginRequest,
    VisitorNotifyUpdate,
    VisitorPasswordUpdate,
    VisitorUserCreate,
)

# ---------------------------------------------------------------------------
# Load runtime config (written by install.sh)
# ---------------------------------------------------------------------------

CONFIG_PATH = Path(os.environ.get("HDY_CONFIG", str(Path(__file__).parent / "config.json")))

def _load_runtime_cfg() -> dict[str, Any]:
    if CONFIG_PATH.exists():
        with open(CONFIG_PATH) as f:
            return json.load(f)
    # Fallback defaults for development
    return {
        "admin_username": "admin",
        "admin_password_hash": CryptContext(schemes=["bcrypt"]).hash("admin"),
        "secret_key": "dev-secret-key-change-me",
        "port": 8080,
        "base_path": "",
    }


_runtime = _load_runtime_cfg()
_pwd_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")
_SECRET_KEY: str = _runtime.get("secret_key", "changeme")
_ALGORITHM = "HS256"
_TOKEN_EXPIRE_HOURS = 24
_CLUSTER_SECRET: str = _runtime.get("cluster_secret", "")
_NODE_ROLE: str = _runtime.get("node_role", "master")

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

BASE_PATH: str = _runtime.get("base_path", "").rstrip("/")

app = FastAPI(title="HDY Monitor", docs_url=None, redoc_url=None)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_STATIC_DIR = Path(__file__).parent / "static"


@app.on_event("startup")
async def _startup() -> None:
    await database.init_db()


# ---------------------------------------------------------------------------
# JWT helpers
# ---------------------------------------------------------------------------

_bearer = HTTPBearer(auto_error=False)


def _create_token() -> str:
    expire = datetime.now(timezone.utc) + timedelta(hours=_TOKEN_EXPIRE_HOURS)
    return jwt.encode({"sub": "admin", "exp": expire}, _SECRET_KEY, algorithm=_ALGORITHM)


def _verify_token(token: str) -> bool:
    try:
        payload = jwt.decode(token, _SECRET_KEY, algorithms=[_ALGORITHM])
        return payload.get("sub") == "admin"
    except JWTError:
        return False


async def require_auth(
    creds: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
) -> None:
    if creds is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
    # Accept admin JWT
    if _verify_token(creds.credentials):
        return
    # Accept cluster secret for node-to-node calls
    if _CLUSTER_SECRET and creds.credentials == _CLUSTER_SECRET:
        return
    raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")


# ---------------------------------------------------------------------------
# Visitor JWT helpers
# ---------------------------------------------------------------------------

_VISITOR_TOKEN_EXPIRE_DAYS = 7


def _create_visitor_token(visitor_id: int) -> str:
    expire = datetime.now(timezone.utc) + timedelta(days=_VISITOR_TOKEN_EXPIRE_DAYS)
    return jwt.encode(
        {"sub": "visitor", "visitor_id": visitor_id, "exp": expire},
        _SECRET_KEY,
        algorithm=_ALGORITHM,
    )


async def require_visitor(
    creds: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
) -> int:
    """Dependency that validates visitor JWT and returns the visitor's user ID."""
    if creds is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
    try:
        payload = jwt.decode(creds.credentials, _SECRET_KEY, algorithms=[_ALGORITHM])
        if payload.get("sub") != "visitor":
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
        visitor_id = payload.get("visitor_id")
        if not visitor_id:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
        return int(visitor_id)
    except JWTError:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")


# ---------------------------------------------------------------------------
# Auth routes (no auth required)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/login", response_model=TokenResponse)
async def login(req: LoginRequest) -> TokenResponse:
    stored_hash: str = _runtime.get("admin_password_hash", "")
    username: str = _runtime.get("admin_username", "admin")

    # Local authentication
    if req.username == username and _pwd_ctx.verify(req.password, stored_hash):
        return TokenResponse(access_token=_create_token())

    # Federated authentication: try registered peer nodes
    if _CLUSTER_SECRET:
        nodes = await database.get_cluster_nodes()
        for node in nodes:
            try:
                async with httpx.AsyncClient(timeout=8, follow_redirects=True) as client:
                    r = await client.post(
                        node["url"].rstrip("/") + "/api/cluster/verify_admin",
                        json={"username": req.username, "password": req.password},
                        headers={
                            "Authorization": f"Bearer {_CLUSTER_SECRET}",
                            "Content-Type": "application/json",
                        },
                    )
                    if r.status_code == 200:
                        body = r.json()
                        if body.get("valid"):
                            # Issue a local token for this cluster admin
                            expire = datetime.now(timezone.utc) + timedelta(hours=_TOKEN_EXPIRE_HOURS)
                            token = jwt.encode(
                                {"sub": "admin", "exp": expire, "cluster_admin": True},
                                _SECRET_KEY,
                                algorithm=_ALGORITHM,
                            )
                            return TokenResponse(access_token=token)
            except Exception:
                continue

    raise HTTPException(status_code=401, detail="Invalid credentials")


# ---------------------------------------------------------------------------
# Site login (proxy to szhdy.com — saves cookie to DB config)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/site_login", dependencies=[Depends(require_auth)])
async def site_login(req: SiteLoginRequest) -> JSONResponse:
    """Log into szhdy.com with username + API key and store the JWT token in config."""
    try:
        async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
            r = await client.post(
                "https://www.szhdy.com/zjmf_api_login",
                json={"username": req.username, "password": req.api_key},
                headers={"Content-Type": "application/json"},
            )
            body: dict = {}
            try:
                body = r.json()
            except Exception:
                pass

            # JWT is in response.data.jwt (preferred) or response.jwt
            body_data = body.get("data")
            jwt_token: str = (
                body_data.get("jwt", "") if isinstance(body_data, dict)
                else body.get("jwt", "")
            )

            if r.status_code == 200 and jwt_token:
                await database.update_config(login_token=jwt_token)
                return JSONResponse({"status": "ok", "message": "登录成功，JWT 已保存"})
            else:
                msg = body.get("msg") or body.get("message") or f"HTTP {r.status_code}"
                return JSONResponse(
                    {"status": "error", "message": f"登录失败：{msg}"},
                    status_code=400,
                )
    except Exception as e:
        raise HTTPException(status_code=502, detail=str(e))


# ---------------------------------------------------------------------------
# Site accounts management
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/site_accounts", dependencies=[Depends(require_auth)])
async def list_site_accounts() -> JSONResponse:
    accounts = await database.get_site_accounts()
    return JSONResponse(accounts)


@app.post(f"{BASE_PATH}/api/site_accounts", dependencies=[Depends(require_auth)])
async def create_site_account(req: SiteAccountCreate) -> JSONResponse:
    """Login to szhdy.com and save the account with its JWT token."""
    try:
        async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
            r = await client.post(
                "https://www.szhdy.com/zjmf_api_login",
                json={"username": req.username, "password": req.api_key},
                headers={"Content-Type": "application/json"},
            )
            body: dict = {}
            try:
                body = r.json()
            except Exception:
                pass

            body_data = body.get("data")
            jwt_token: str = (
                body_data.get("jwt", "") if isinstance(body_data, dict)
                else body.get("jwt", "")
            )

            if r.status_code == 200 and jwt_token:
                label = req.label or req.username
                account_id = await database.add_site_account(label, req.username, req.api_key, jwt_token)
                return JSONResponse({"status": "ok", "id": account_id, "message": "账号已保存"})
            else:
                msg = body.get("msg") or body.get("message") or f"HTTP {r.status_code}"
                return JSONResponse(
                    {"status": "error", "message": f"登录失败：{msg}"},
                    status_code=400,
                )
    except Exception as e:
        raise HTTPException(status_code=502, detail=str(e))


@app.delete(f"{BASE_PATH}/api/site_accounts/{{account_id}}", dependencies=[Depends(require_auth)])
async def remove_site_account(account_id: int) -> JSONResponse:
    await database.delete_site_account(account_id)
    return JSONResponse({"status": "ok"})


@app.post(f"{BASE_PATH}/api/site_accounts/{{account_id}}/activate", dependencies=[Depends(require_auth)])
async def activate_site_account(account_id: int) -> JSONResponse:
    await database.set_active_site_account(account_id)
    return JSONResponse({"status": "ok", "message": "已切换为当前账号"})


# ---------------------------------------------------------------------------
# Config routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/config", dependencies=[Depends(require_auth)])
async def get_config() -> JSONResponse:
    cfg = await database.get_config()
    # Don't expose full token/cookie to frontend
    cfg_out = {k: v for k, v in cfg.items() if k not in ("login_cookie", "login_token")}
    cfg_out["has_cookie"] = bool(cfg.get("login_cookie"))
    cfg_out["has_token"] = bool(cfg.get("login_token"))
    cfg_out["site_title"] = cfg.get("site_title") or ""
    cfg_out["node_role"] = _NODE_ROLE
    cfg_out["has_cluster_secret"] = bool(_CLUSTER_SECRET)
    return JSONResponse(cfg_out)


@app.put(f"{BASE_PATH}/api/config", dependencies=[Depends(require_auth)])
async def update_config(body: ConfigUpdate) -> JSONResponse:
    update: dict[str, Any] = {}
    provided = getattr(body, "model_fields_set", set()) or getattr(body, "__fields_set__", set())
    if "start_pid" in provided and body.start_pid is not None:
        update["start_pid"] = body.start_pid
    if "end_pid" in provided and body.end_pid is not None:
        update["end_pid"] = body.end_pid
    if "exec_start_pid" in provided:
        update["exec_start_pid"] = body.exec_start_pid
    if "interval_ms" in provided and body.interval_ms is not None:
        update["interval_ms"] = max(500, body.interval_ms)
    if "loop_enabled" in provided and body.loop_enabled is not None:
        update["loop_enabled"] = body.loop_enabled
    if "login_cookie" in provided:
        update["login_cookie"] = body.login_cookie
    if "notify_channels" in provided and body.notify_channels is not None:
        update["notify_channels"] = body.notify_channels
    if "notify_price_min" in provided:
        update["notify_price_min"] = body.notify_price_min
    if "notify_price_max" in provided:
        update["notify_price_max"] = body.notify_price_max
    if "notify_monthly_price_min" in provided:
        update["notify_monthly_price_min"] = body.notify_monthly_price_min
    if "notify_monthly_price_max" in provided:
        update["notify_monthly_price_max"] = body.notify_monthly_price_max
    if "site_title" in provided:
        update["site_title"] = body.site_title or ""
    if "scan_reverse" in provided and body.scan_reverse is not None:
        update["scan_reverse"] = body.scan_reverse
    await database.update_config(**update)
    return JSONResponse({"status": "ok"})


# ---------------------------------------------------------------------------
# Crawler routes
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/crawler/start", dependencies=[Depends(require_auth)])
async def start_crawler() -> JSONResponse:
    started = crawler.start_crawler()
    return JSONResponse({"started": started})


@app.post(f"{BASE_PATH}/api/crawler/stop", dependencies=[Depends(require_auth)])
async def stop_crawler() -> JSONResponse:
    await crawler.stop_crawler()
    return JSONResponse({"stopped": True})


@app.post(f"{BASE_PATH}/api/notify/toggle_pause", dependencies=[Depends(require_auth)])
async def toggle_notify_pause() -> JSONResponse:
    """Toggle notification pause for the current crawl round.
    Auto-resets to unpaused at the start of the next round."""
    paused = crawler.toggle_notify_pause()
    return JSONResponse({"notify_paused": paused})


@app.post(f"{BASE_PATH}/api/notify/toggle_filter_sold_out", dependencies=[Depends(require_auth)])
async def toggle_filter_sold_out() -> JSONResponse:
    """Toggle sold-out notification filter. When enabled, out_of_stock notifications are suppressed."""
    filter_sold_out = crawler.toggle_filter_sold_out()
    return JSONResponse({"filter_sold_out": filter_sold_out})


@app.get(f"{BASE_PATH}/api/crawler/status", dependencies=[Depends(require_auth)])
async def crawler_status() -> CrawlerStatus:
    status_obj = crawler.get_status()
    cfg = await database.get_config()
    status_obj.start_pid = cfg.get("start_pid")
    status_obj.end_pid = cfg.get("end_pid")
    status_obj.exec_start_pid = cfg.get("exec_start_pid")
    status_obj.loop_enabled = cfg.get("loop_enabled", False)
    status_obj.notify_paused = crawler.state.notify_paused
    status_obj.filter_sold_out = crawler.state.filter_sold_out
    return status_obj


# ---------------------------------------------------------------------------
# Product routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/products", dependencies=[Depends(require_auth)])
async def list_products(
    page: int = 1,
    page_size: int = 20,
    name: Optional[str] = None,
    stock_status: Optional[str] = None,
    billingcycle: Optional[str] = None,
    price_min: Optional[float] = None,
    price_max: Optional[float] = None,
    sort_price: Optional[str] = None,
) -> JSONResponse:
    page_size = min(max(page_size, 1), 200)
    offset = (page - 1) * page_size
    sort_price = sort_price if sort_price in ("asc", "desc") else None
    products = await database.get_products(
        limit=page_size,
        offset=offset,
        name=name,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
        sort_price=sort_price,
    )
    total = await database.count_products(
        name=name,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
    )
    return JSONResponse({"total": total, "page": page, "page_size": page_size, "items": products})


@app.get(f"{BASE_PATH}/api/products/filter_options", dependencies=[Depends(require_auth)])
async def product_filter_options() -> JSONResponse:
    opts = await database.get_product_filter_options()
    return JSONResponse(opts)


@app.get(f"{BASE_PATH}/api/products/{{pid}}/history", dependencies=[Depends(require_auth)])
async def product_history(pid: int, page: int = 1, page_size: int = 50) -> PaginatedChanges:
    total, items = await database.get_changes(pid=pid, page=page, page_size=page_size)
    return PaginatedChanges(
        total=total,
        page=page,
        page_size=page_size,
        items=[ChangeLog(**i) for i in items],
    )


# ---------------------------------------------------------------------------
# Changes route
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/changes", dependencies=[Depends(require_auth)])
async def list_changes(page: int = 1, page_size: int = 50) -> PaginatedChanges:
    total, items = await database.get_changes(page=page, page_size=page_size)
    return PaginatedChanges(
        total=total,
        page=page,
        page_size=page_size,
        items=[ChangeLog(**i) for i in items],
    )


@app.delete(f"{BASE_PATH}/api/changes", dependencies=[Depends(require_auth)])
async def delete_changes() -> JSONResponse:
    await database.clear_changes()
    return JSONResponse({"status": "ok"})


# ---------------------------------------------------------------------------
# Notify test route
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/notify/test", dependencies=[Depends(require_auth)])
async def test_notify(req: NotifyTestRequest) -> JSONResponse:
    success = await notifier.send_channel(
        req.channel, req.config, title="HDY Monitor 测试通知", body="通知渠道配置成功！"
    )
    return JSONResponse({"success": success})


# ---------------------------------------------------------------------------
# Backup & Restore routes
# ---------------------------------------------------------------------------

_SQLITE_MAGIC = b"SQLite format 3\x00"


@app.get(f"{BASE_PATH}/api/backup", dependencies=[Depends(require_auth)])
async def download_backup() -> FileResponse:
    """Download the full SQLite database as a backup file."""
    if not os.path.exists(database.DB_PATH):
        raise HTTPException(status_code=404, detail="数据库文件不存在")
    return FileResponse(
        database.DB_PATH,
        media_type="application/octet-stream",
        filename="hdy_backup.db",
    )


@app.post(f"{BASE_PATH}/api/restore", dependencies=[Depends(require_auth)])
async def restore_backup(file: UploadFile = File(...)) -> JSONResponse:
    """Upload a previously downloaded backup and replace the current database."""
    content = await file.read()
    if not content.startswith(_SQLITE_MAGIC):
        raise HTTPException(status_code=400, detail="不是有效的 SQLite 数据库文件")

    # Stop the crawler before replacing the DB
    await crawler.stop_crawler()

    db_dir = os.path.dirname(os.path.abspath(database.DB_PATH))
    try:
        with tempfile.NamedTemporaryFile(dir=db_dir, delete=False, suffix=".tmp") as tmp:
            tmp.write(content)
            tmp_path = tmp.name
        os.replace(tmp_path, database.DB_PATH)
        # Re-run migrations to ensure schema is up to date
        await database.init_db()
    except Exception as e:
        try:
            os.remove(tmp_path)
        except Exception:
            pass
        raise HTTPException(status_code=500, detail=str(e))

    return JSONResponse({"status": "ok", "message": "数据库已恢复，请刷新页面"})


# ---------------------------------------------------------------------------
# Admin — visitor user management routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/visitors", dependencies=[Depends(require_auth)])
async def list_visitors() -> JSONResponse:
    visitors = await database.get_visitor_users()
    return JSONResponse(visitors)


@app.post(f"{BASE_PATH}/api/visitors", dependencies=[Depends(require_auth)])
async def create_visitor(req: VisitorUserCreate) -> JSONResponse:
    username = req.username.strip()
    if not username or not req.password:
        raise HTTPException(status_code=400, detail="账号和密码不能为空")
    existing = await database.get_visitor_by_username(username)
    if existing:
        raise HTTPException(status_code=409, detail="该账号已存在")
    password_hash = _pwd_ctx.hash(req.password)
    visitor_id = await database.create_visitor_user(username, password_hash, req.label)
    return JSONResponse({"status": "ok", "id": visitor_id, "message": "访客账号已创建"})


@app.delete(f"{BASE_PATH}/api/visitors/{{visitor_id}}", dependencies=[Depends(require_auth)])
async def delete_visitor(visitor_id: int) -> JSONResponse:
    await database.delete_visitor_user(visitor_id)
    return JSONResponse({"status": "ok"})


@app.put(f"{BASE_PATH}/api/visitors/{{visitor_id}}/password", dependencies=[Depends(require_auth)])
async def reset_visitor_password(visitor_id: int, req: VisitorPasswordUpdate) -> JSONResponse:
    if not req.password:
        raise HTTPException(status_code=400, detail="密码不能为空")
    password_hash = _pwd_ctx.hash(req.password)
    await database.update_visitor_password(visitor_id, password_hash)
    return JSONResponse({"status": "ok", "message": "密码已重置"})


# ---------------------------------------------------------------------------
# Visitor — public routes (visitor JWT required)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/visitor/login", response_model=TokenResponse)
async def visitor_login(req: VisitorLoginRequest) -> TokenResponse:
    visitor = await database.get_visitor_by_username(req.username.strip())
    if not visitor or not visitor.get("is_active"):
        raise HTTPException(status_code=401, detail="账号或密码错误")
    if not _pwd_ctx.verify(req.password, visitor.get("password_hash", "")):
        raise HTTPException(status_code=401, detail="账号或密码错误")
    token = _create_visitor_token(visitor["id"])
    return TokenResponse(access_token=token)


@app.get(f"{BASE_PATH}/api/visitor/me")
async def visitor_me(visitor_id: int = Depends(require_visitor)) -> JSONResponse:
    visitor = await database.get_visitor_by_id(visitor_id)
    if not visitor:
        raise HTTPException(status_code=404, detail="访客账号不存在")
    return JSONResponse(visitor)


@app.put(f"{BASE_PATH}/api/visitor/me/notify")
async def visitor_update_notify(
    req: VisitorNotifyUpdate,
    visitor_id: int = Depends(require_visitor),
) -> JSONResponse:
    await database.update_visitor_notify(
        visitor_id,
        req.notify_channels,
        req.notify_price_min,
        req.notify_price_max,
        req.notify_monthly_price_min,
        req.notify_monthly_price_max,
    )
    return JSONResponse({"status": "ok"})


@app.post(f"{BASE_PATH}/api/visitor/notify/test")
async def visitor_test_notify(
    req: NotifyTestRequest,
    visitor_id: int = Depends(require_visitor),
) -> JSONResponse:
    success = await notifier.send_channel(
        req.channel, req.config, title="HDY Monitor 测试通知", body="通知渠道配置成功！"
    )
    return JSONResponse({"success": success})


@app.get(f"{BASE_PATH}/api/visitor/products")
async def visitor_list_products(
    page: int = 1,
    page_size: int = 20,
    name: Optional[str] = None,
    stock_status: Optional[str] = None,
    billingcycle: Optional[str] = None,
    price_min: Optional[float] = None,
    price_max: Optional[float] = None,
    sort_price: Optional[str] = None,
    visitor_id: int = Depends(require_visitor),
) -> JSONResponse:
    page_size = min(max(page_size, 1), 200)
    offset = (page - 1) * page_size
    sort_price = sort_price if sort_price in ("asc", "desc") else None
    products = await database.get_products(
        limit=page_size,
        offset=offset,
        name=name,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
        sort_price=sort_price,
    )
    total = await database.count_products(
        name=name,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
    )
    return JSONResponse({"total": total, "page": page, "page_size": page_size, "items": products})


@app.get(f"{BASE_PATH}/api/visitor/products/filter_options")
async def visitor_product_filter_options(
    visitor_id: int = Depends(require_visitor),
) -> JSONResponse:
    opts = await database.get_product_filter_options()
    return JSONResponse(opts)


# ---------------------------------------------------------------------------
# Cluster — inter-node communication routes (authenticated by cluster_secret)
# ---------------------------------------------------------------------------

def _require_cluster_secret(
    creds: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
) -> None:
    """Dependency: only accepts requests carrying the shared cluster_secret."""
    if not _CLUSTER_SECRET:
        raise HTTPException(status_code=503, detail="Cluster not configured on this node")
    if creds is None or creds.credentials != _CLUSTER_SECRET:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid cluster secret")


@app.get(f"{BASE_PATH}/api/cluster/info", dependencies=[Depends(_require_cluster_secret)])
async def cluster_info() -> JSONResponse:
    """Return basic information about this node. Used for ping/health checks."""
    return JSONResponse({
        "status": "ok",
        "node_role": _NODE_ROLE,
        "version": "1.1.1",
    })


@app.post(f"{BASE_PATH}/api/cluster/verify_admin", dependencies=[Depends(_require_cluster_secret)])
async def cluster_verify_admin(req: ClusterVerifyAdminRequest) -> JSONResponse:
    """Verify admin credentials for federated login. Returns {valid: true/false}."""
    stored_hash: str = _runtime.get("admin_password_hash", "")
    username: str = _runtime.get("admin_username", "admin")
    valid = (req.username == username and _pwd_ctx.verify(req.password, stored_hash))
    return JSONResponse({"valid": valid})


@app.post(f"{BASE_PATH}/api/cluster/sync", dependencies=[Depends(_require_cluster_secret)])
async def cluster_sync(req: ClusterSyncRequest) -> JSONResponse:
    """Receive a products + change_log sync payload from a peer node."""
    await database.bulk_upsert_products(req.products)
    await database.bulk_insert_changes(req.changes)
    return JSONResponse({
        "status": "ok",
        "products_received": len(req.products),
        "changes_received": len(req.changes),
    })


# ---------------------------------------------------------------------------
# Admin — cluster node management routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/nodes", dependencies=[Depends(require_auth)])
async def list_nodes() -> JSONResponse:
    nodes = await database.get_cluster_nodes()
    return JSONResponse(nodes)


@app.post(f"{BASE_PATH}/api/nodes", dependencies=[Depends(require_auth)])
async def add_node(req: NodeCreate) -> JSONResponse:
    url = req.url.rstrip("/")
    if not url.startswith("http"):
        raise HTTPException(status_code=400, detail="URL 必须以 http:// 或 https:// 开头")

    # Verify connectivity using the cluster_secret
    initial_status = "unknown"
    version = None
    if _CLUSTER_SECRET:
        try:
            async with httpx.AsyncClient(timeout=8, follow_redirects=True) as client:
                r = await client.get(
                    url + "/api/cluster/info",
                    headers={"Authorization": f"Bearer {_CLUSTER_SECRET}"},
                )
                if r.status_code == 200:
                    info_body = r.json()
                    initial_status = "online"
                    version = info_body.get("version")
                else:
                    initial_status = "error"
        except Exception:
            initial_status = "unreachable"

    node_id = await database.add_cluster_node(req.label, url, req.role)
    if initial_status != "unknown":
        await database.update_cluster_node_status(node_id, initial_status, version)

    return JSONResponse({
        "status": "ok",
        "id": node_id,
        "connectivity": initial_status,
        "message": "节点已添加" + ("" if initial_status == "online" else "（连通性检测失败，请确认集群密钥和地址是否正确）"),
    })


@app.delete(f"{BASE_PATH}/api/nodes/{{node_id}}", dependencies=[Depends(require_auth)])
async def remove_node(node_id: int) -> JSONResponse:
    await database.delete_cluster_node(node_id)
    return JSONResponse({"status": "ok"})


@app.post(f"{BASE_PATH}/api/nodes/{{node_id}}/ping", dependencies=[Depends(require_auth)])
async def ping_node(node_id: int) -> JSONResponse:
    node = await database.get_cluster_node_by_id(node_id)
    if not node:
        raise HTTPException(status_code=404, detail="节点不存在")

    if not _CLUSTER_SECRET:
        return JSONResponse({"status": "error", "message": "本节点未配置集群密钥"})

    try:
        async with httpx.AsyncClient(timeout=8, follow_redirects=True) as client:
            r = await client.get(
                node["url"].rstrip("/") + "/api/cluster/info",
                headers={"Authorization": f"Bearer {_CLUSTER_SECRET}"},
            )
            if r.status_code == 200:
                info_body = r.json()
                await database.update_cluster_node_status(
                    node_id, "online", info_body.get("version")
                )
                return JSONResponse({"status": "ok", "info": info_body})
            else:
                await database.update_cluster_node_status(node_id, "error")
                return JSONResponse({"status": "error", "http_status": r.status_code})
    except Exception:
        await database.update_cluster_node_status(node_id, "unreachable")
        return JSONResponse({"status": "unreachable", "message": "节点连接失败"})


@app.post(f"{BASE_PATH}/api/nodes/{{node_id}}/proxy", dependencies=[Depends(require_auth)])
async def proxy_to_node(node_id: int, req: ClusterProxyRequest) -> JSONResponse:
    """Forward any API request to a registered cluster node."""
    node = await database.get_cluster_node_by_id(node_id)
    if not node:
        raise HTTPException(status_code=404, detail="节点不存在")

    if not _CLUSTER_SECRET:
        raise HTTPException(status_code=503, detail="本节点未配置集群密钥，无法代理请求")

    target_url = node["url"].rstrip("/") + req.path
    method = req.method.upper()

    # Validate the path to prevent SSRF: must start with /api/ and contain no scheme
    if not req.path.startswith("/api/") or "://" in req.path:
        raise HTTPException(status_code=400, detail="无效的代理路径：必须以 /api/ 开头")

    try:
        async with httpx.AsyncClient(timeout=30, follow_redirects=False) as client:
            kwargs: dict[str, Any] = {
                "headers": {
                    "Authorization": f"Bearer {_CLUSTER_SECRET}",
                    "Content-Type": "application/json",
                }
            }
            if req.body is not None and method not in ("GET", "HEAD", "DELETE"):
                kwargs["json"] = req.body
            r = await client.request(method, target_url, **kwargs)
            try:
                content = r.json()
            except Exception:
                content = {"raw": r.text}
            return JSONResponse(content=content, status_code=r.status_code)
    except Exception:
        raise HTTPException(status_code=502, detail="代理请求失败")


@app.post(f"{BASE_PATH}/api/nodes/{{node_id}}/push_sync", dependencies=[Depends(require_auth)])
async def push_sync_to_node(node_id: int) -> JSONResponse:
    """Push local products and change_log data to a registered node."""
    node = await database.get_cluster_node_by_id(node_id)
    if not node:
        raise HTTPException(status_code=404, detail="节点不存在")

    if not _CLUSTER_SECRET:
        raise HTTPException(status_code=503, detail="本节点未配置集群密钥")

    products = await database.export_products_for_sync()
    changes = await database.export_changes_for_sync()

    try:
        async with httpx.AsyncClient(timeout=60, follow_redirects=True) as client:
            r = await client.post(
                node["url"].rstrip("/") + "/api/cluster/sync",
                json={"products": products, "changes": changes},
                headers={
                    "Authorization": f"Bearer {_CLUSTER_SECRET}",
                    "Content-Type": "application/json",
                },
            )
            if r.status_code == 200:
                result = r.json()
                return JSONResponse({"status": "ok", **result})
            else:
                return JSONResponse(
                    {"status": "error", "message": f"目标节点返回 HTTP {r.status_code}"},
                    status_code=502,
                )
    except Exception:
        raise HTTPException(status_code=502, detail="同步失败")


_ASSETS_DIR = _STATIC_DIR / "assets"

if _STATIC_DIR.exists():
    # Serve static assets (only mount if the assets subdirectory exists)
    if _ASSETS_DIR.exists():
        app.mount(f"{BASE_PATH}/assets", StaticFiles(directory=str(_ASSETS_DIR)), name="assets")

    @app.get(f"{BASE_PATH}/", include_in_schema=False)
    @app.get(f"{BASE_PATH}", include_in_schema=False)
    async def serve_index() -> FileResponse:
        return FileResponse(str(_STATIC_DIR / "index.html"))

    @app.get(f"{BASE_PATH}/visitor", include_in_schema=False)
    @app.get(f"{BASE_PATH}/visitor/", include_in_schema=False)
    async def serve_visitor_page() -> FileResponse:
        vf = _STATIC_DIR / "visitor.html"
        if not vf.exists():
            raise HTTPException(status_code=404)
        return FileResponse(str(vf))

    # Catch-all for SPA routing
    @app.get(f"{BASE_PATH}/{{full_path:path}}", include_in_schema=False)
    async def spa_fallback(full_path: str) -> FileResponse:
        if full_path.startswith("api/"):
            raise HTTPException(status_code=404)
        return FileResponse(str(_STATIC_DIR / "index.html"))
