"""
FastAPI application — HDY Monitor backend.

Authentication: single-user JWT.
Credentials and other settings are read from config.json generated by install.sh.
"""
from __future__ import annotations

import json
import logging
import os
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional

import httpx
from fastapi import Depends, FastAPI, HTTPException, Request, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from fastapi.staticfiles import StaticFiles
from jose import JWTError, jwt
from passlib.context import CryptContext

import crawler
import database
import notifier
from models import (
    ChangeLog,
    ConfigUpdate,
    CrawlerStatus,
    LoginRequest,
    NotifyTestRequest,
    PaginatedChanges,
    PaginatedProducts,
    SiteAccount,
    SiteAccountCreate,
    SiteLoginRequest,
    TokenResponse,
)

# ---------------------------------------------------------------------------
# Load runtime config (written by install.sh)
# ---------------------------------------------------------------------------

CONFIG_PATH = Path(os.environ.get("HDY_CONFIG", str(Path(__file__).parent / "config.json")))

def _load_runtime_cfg() -> dict[str, Any]:
    if CONFIG_PATH.exists():
        with open(CONFIG_PATH) as f:
            return json.load(f)
    # Fallback defaults for development
    return {
        "admin_username": "admin",
        "admin_password_hash": CryptContext(schemes=["bcrypt"]).hash("admin"),
        "secret_key": "dev-secret-key-change-me",
        "port": 8080,
        "base_path": "",
    }


_runtime = _load_runtime_cfg()
_pwd_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")
_SECRET_KEY: str = _runtime.get("secret_key", "changeme")
_ALGORITHM = "HS256"
_TOKEN_EXPIRE_HOURS = 24

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

BASE_PATH: str = _runtime.get("base_path", "").rstrip("/")

app = FastAPI(title="HDY Monitor", docs_url=None, redoc_url=None)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_STATIC_DIR = Path(__file__).parent / "static"


@app.on_event("startup")
async def _startup() -> None:
    await database.init_db()


# ---------------------------------------------------------------------------
# JWT helpers
# ---------------------------------------------------------------------------

_bearer = HTTPBearer(auto_error=False)


def _create_token() -> str:
    expire = datetime.now(timezone.utc) + timedelta(hours=_TOKEN_EXPIRE_HOURS)
    return jwt.encode({"sub": "admin", "exp": expire}, _SECRET_KEY, algorithm=_ALGORITHM)


def _verify_token(token: str) -> bool:
    try:
        payload = jwt.decode(token, _SECRET_KEY, algorithms=[_ALGORITHM])
        return payload.get("sub") == "admin"
    except JWTError:
        return False


async def require_auth(
    creds: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
) -> None:
    if creds is None or not _verify_token(creds.credentials):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")


# ---------------------------------------------------------------------------
# Auth routes (no auth required)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/login", response_model=TokenResponse)
async def login(req: LoginRequest) -> TokenResponse:
    stored_hash: str = _runtime.get("admin_password_hash", "")
    username: str = _runtime.get("admin_username", "admin")

    if req.username != username or not _pwd_ctx.verify(req.password, stored_hash):
        raise HTTPException(status_code=401, detail="Invalid credentials")

    return TokenResponse(access_token=_create_token())


# ---------------------------------------------------------------------------
# Site login (proxy to szhdy.com — saves cookie to DB config)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/site_login", dependencies=[Depends(require_auth)])
async def site_login(req: SiteLoginRequest) -> JSONResponse:
    """Log into szhdy.com with username + API key and store the JWT token in config."""
    try:
        async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
            r = await client.post(
                "https://www.szhdy.com/zjmf_api_login",
                json={"username": req.username, "password": req.api_key},
                headers={"Content-Type": "application/json"},
            )
            body: dict = {}
            try:
                body = r.json()
            except Exception:
                pass

            # JWT is in response.data.jwt (preferred) or response.jwt
            body_data = body.get("data")
            jwt_token: str = (
                body_data.get("jwt", "") if isinstance(body_data, dict)
                else body.get("jwt", "")
            )

            if r.status_code == 200 and jwt_token:
                await database.update_config(login_token=jwt_token)
                return JSONResponse({"status": "ok", "message": "登录成功，JWT 已保存"})
            else:
                msg = body.get("msg") or body.get("message") or f"HTTP {r.status_code}"
                return JSONResponse(
                    {"status": "error", "message": f"登录失败：{msg}"},
                    status_code=400,
                )
    except Exception as e:
        raise HTTPException(status_code=502, detail=str(e))


# ---------------------------------------------------------------------------
# Site accounts management
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/site_accounts", dependencies=[Depends(require_auth)])
async def list_site_accounts() -> JSONResponse:
    accounts = await database.get_site_accounts()
    return JSONResponse(accounts)


@app.post(f"{BASE_PATH}/api/site_accounts", dependencies=[Depends(require_auth)])
async def create_site_account(req: SiteAccountCreate) -> JSONResponse:
    """Login to szhdy.com and save the account with its JWT token."""
    try:
        async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
            r = await client.post(
                "https://www.szhdy.com/zjmf_api_login",
                json={"username": req.username, "password": req.api_key},
                headers={"Content-Type": "application/json"},
            )
            body: dict = {}
            try:
                body = r.json()
            except Exception:
                pass

            body_data = body.get("data")
            jwt_token: str = (
                body_data.get("jwt", "") if isinstance(body_data, dict)
                else body.get("jwt", "")
            )

            if r.status_code == 200 and jwt_token:
                label = req.label or req.username
                account_id = await database.add_site_account(label, req.username, jwt_token)
                return JSONResponse({"status": "ok", "id": account_id, "message": "账号已保存"})
            else:
                msg = body.get("msg") or body.get("message") or f"HTTP {r.status_code}"
                return JSONResponse(
                    {"status": "error", "message": f"登录失败：{msg}"},
                    status_code=400,
                )
    except Exception as e:
        raise HTTPException(status_code=502, detail=str(e))


@app.delete(f"{BASE_PATH}/api/site_accounts/{{account_id}}", dependencies=[Depends(require_auth)])
async def remove_site_account(account_id: int) -> JSONResponse:
    await database.delete_site_account(account_id)
    return JSONResponse({"status": "ok"})


@app.post(f"{BASE_PATH}/api/site_accounts/{{account_id}}/activate", dependencies=[Depends(require_auth)])
async def activate_site_account(account_id: int) -> JSONResponse:
    await database.set_active_site_account(account_id)
    return JSONResponse({"status": "ok", "message": "已切换为当前账号"})


# ---------------------------------------------------------------------------
# Config routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/config", dependencies=[Depends(require_auth)])
async def get_config() -> JSONResponse:
    cfg = await database.get_config()
    # Don't expose full token/cookie to frontend
    cfg_out = {k: v for k, v in cfg.items() if k not in ("login_cookie", "login_token")}
    cfg_out["has_cookie"] = bool(cfg.get("login_cookie"))
    cfg_out["has_token"] = bool(cfg.get("login_token"))
    return JSONResponse(cfg_out)


@app.put(f"{BASE_PATH}/api/config", dependencies=[Depends(require_auth)])
async def update_config(body: ConfigUpdate) -> JSONResponse:
    update: dict[str, Any] = {}
    if body.start_pid is not None:
        update["start_pid"] = body.start_pid
    if body.end_pid is not None:
        update["end_pid"] = body.end_pid
    if body.exec_start_pid is not None:
        update["exec_start_pid"] = body.exec_start_pid
    if body.interval_ms is not None:
        update["interval_ms"] = max(500, body.interval_ms)
    if body.loop_enabled is not None:
        update["loop_enabled"] = body.loop_enabled
    if body.login_cookie is not None:
        update["login_cookie"] = body.login_cookie
    if body.notify_channels is not None:
        update["notify_channels"] = body.notify_channels
    await database.update_config(**update)
    return JSONResponse({"status": "ok"})


# ---------------------------------------------------------------------------
# Crawler routes
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/crawler/start", dependencies=[Depends(require_auth)])
async def start_crawler() -> JSONResponse:
    started = crawler.start_crawler()
    return JSONResponse({"started": started})


@app.post(f"{BASE_PATH}/api/crawler/stop", dependencies=[Depends(require_auth)])
async def stop_crawler() -> JSONResponse:
    await crawler.stop_crawler()
    return JSONResponse({"stopped": True})


@app.get(f"{BASE_PATH}/api/crawler/status", dependencies=[Depends(require_auth)])
async def crawler_status() -> CrawlerStatus:
    status_obj = crawler.get_status()
    cfg = await database.get_config()
    status_obj.start_pid = cfg.get("start_pid")
    status_obj.end_pid = cfg.get("end_pid")
    status_obj.exec_start_pid = cfg.get("exec_start_pid")
    status_obj.loop_enabled = cfg.get("loop_enabled", False)
    return status_obj


# ---------------------------------------------------------------------------
# Product routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/products", dependencies=[Depends(require_auth)])
async def list_products(
    page: int = 1,
    page_size: int = 20,
    region: Optional[str] = None,
    stock_status: Optional[str] = None,
    billingcycle: Optional[str] = None,
    price_min: Optional[float] = None,
    price_max: Optional[float] = None,
) -> JSONResponse:
    page_size = min(max(page_size, 1), 200)
    offset = (page - 1) * page_size
    products = await database.get_products(
        limit=page_size,
        offset=offset,
        region=region,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
    )
    total = await database.count_products(
        region=region,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
    )
    return JSONResponse({"total": total, "page": page, "page_size": page_size, "items": products})


@app.get(f"{BASE_PATH}/api/products/filter_options", dependencies=[Depends(require_auth)])
async def product_filter_options() -> JSONResponse:
    opts = await database.get_product_filter_options()
    return JSONResponse(opts)


@app.get(f"{BASE_PATH}/api/products/{{pid}}/history", dependencies=[Depends(require_auth)])
async def product_history(pid: int, page: int = 1, page_size: int = 50) -> PaginatedChanges:
    total, items = await database.get_changes(pid=pid, page=page, page_size=page_size)
    return PaginatedChanges(
        total=total,
        page=page,
        page_size=page_size,
        items=[ChangeLog(**i) for i in items],
    )


# ---------------------------------------------------------------------------
# Changes route
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/changes", dependencies=[Depends(require_auth)])
async def list_changes(page: int = 1, page_size: int = 50) -> PaginatedChanges:
    total, items = await database.get_changes(page=page, page_size=page_size)
    return PaginatedChanges(
        total=total,
        page=page,
        page_size=page_size,
        items=[ChangeLog(**i) for i in items],
    )


@app.delete(f"{BASE_PATH}/api/changes", dependencies=[Depends(require_auth)])
async def delete_changes() -> JSONResponse:
    await database.clear_changes()
    return JSONResponse({"status": "ok"})


# ---------------------------------------------------------------------------
# Notify test route
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/notify/test", dependencies=[Depends(require_auth)])
async def test_notify(req: NotifyTestRequest) -> JSONResponse:
    success = await notifier.send_channel(
        req.channel, req.config, title="HDY Monitor 测试通知", body="通知渠道配置成功！"
    )
    return JSONResponse({"success": success})


# ---------------------------------------------------------------------------
# Static files & SPA fallback
# ---------------------------------------------------------------------------

_ASSETS_DIR = _STATIC_DIR / "assets"

if _STATIC_DIR.exists():
    # Serve static assets (only mount if the assets subdirectory exists)
    if _ASSETS_DIR.exists():
        app.mount(f"{BASE_PATH}/assets", StaticFiles(directory=str(_ASSETS_DIR)), name="assets")

    @app.get(f"{BASE_PATH}/", include_in_schema=False)
    @app.get(f"{BASE_PATH}", include_in_schema=False)
    async def serve_index() -> FileResponse:
        return FileResponse(str(_STATIC_DIR / "index.html"))

    # Catch-all for SPA routing
    @app.get(f"{BASE_PATH}/{{full_path:path}}", include_in_schema=False)
    async def spa_fallback(full_path: str) -> FileResponse:
        if full_path.startswith("api/"):
            raise HTTPException(status_code=404)
        return FileResponse(str(_STATIC_DIR / "index.html"))
