"""
FastAPI application — HDY Monitor backend.

Authentication: single-user JWT.
Credentials and other settings are read from config.json generated by install.sh.
"""
from __future__ import annotations

import json
import logging
import os
import secrets
import shutil
import tempfile
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Optional

import httpx
from fastapi import Depends, FastAPI, File, HTTPException, Request, UploadFile, status
from fastapi.middleware.cors import CORSMiddleware
from fastapi.responses import FileResponse, JSONResponse, PlainTextResponse
from fastapi.security import HTTPAuthorizationCredentials, HTTPBearer
from fastapi.staticfiles import StaticFiles
from jose import JWTError, jwt
from passlib.context import CryptContext

import crawler
import database
import notifier
from models import (
    AgentCreate,
    AgentHeartbeatRequest,
    AgentReportRequest,
    AgentTaskAssign,
    ChangeLog,
    ConfigUpdate,
    CrawlerStatus,
    LoginRequest,
    NotifyTestRequest,
    PaginatedChanges,
    PaginatedProducts,
    SiteAccount,
    SiteAccountCreate,
    SiteLoginRequest,
    TokenResponse,
    VisitorLoginRequest,
    VisitorNotifyUpdate,
    VisitorPasswordUpdate,
    VisitorUserCreate,
)

# ---------------------------------------------------------------------------
# Load runtime config (written by install.sh)
# ---------------------------------------------------------------------------

CONFIG_PATH = Path(os.environ.get("HDY_CONFIG", str(Path(__file__).parent / "config.json")))

def _load_runtime_cfg() -> dict[str, Any]:
    if CONFIG_PATH.exists():
        with open(CONFIG_PATH) as f:
            return json.load(f)
    # Fallback defaults for development
    return {
        "admin_username": "admin",
        "admin_password_hash": CryptContext(schemes=["bcrypt"]).hash("admin"),
        "secret_key": "dev-secret-key-change-me",
        "port": 8080,
        "base_path": "",
    }


_runtime = _load_runtime_cfg()
_pwd_ctx = CryptContext(schemes=["bcrypt"], deprecated="auto")
_SECRET_KEY: str = _runtime.get("secret_key", "changeme")
_ALGORITHM = "HS256"
_TOKEN_EXPIRE_HOURS = 24

# ---------------------------------------------------------------------------
# Logging
# ---------------------------------------------------------------------------

logging.basicConfig(
    level=logging.INFO,
    format="%(asctime)s [%(levelname)s] %(name)s: %(message)s",
)

# ---------------------------------------------------------------------------
# App factory
# ---------------------------------------------------------------------------

BASE_PATH: str = _runtime.get("base_path", "").rstrip("/")

app = FastAPI(title="HDY Monitor", docs_url=None, redoc_url=None)
app.add_middleware(
    CORSMiddleware,
    allow_origins=["*"],
    allow_credentials=True,
    allow_methods=["*"],
    allow_headers=["*"],
)

_STATIC_DIR = Path(__file__).parent / "static"


@app.on_event("startup")
async def _startup() -> None:
    await database.init_db()


# ---------------------------------------------------------------------------
# JWT helpers
# ---------------------------------------------------------------------------

_bearer = HTTPBearer(auto_error=False)


def _create_token() -> str:
    expire = datetime.now(timezone.utc) + timedelta(hours=_TOKEN_EXPIRE_HOURS)
    return jwt.encode({"sub": "admin", "exp": expire}, _SECRET_KEY, algorithm=_ALGORITHM)


def _verify_token(token: str) -> bool:
    try:
        payload = jwt.decode(token, _SECRET_KEY, algorithms=[_ALGORITHM])
        return payload.get("sub") == "admin"
    except JWTError:
        return False


async def require_auth(
    creds: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
) -> None:
    if creds is None or not _verify_token(creds.credentials):
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")


# ---------------------------------------------------------------------------
# Visitor JWT helpers
# ---------------------------------------------------------------------------

_VISITOR_TOKEN_EXPIRE_DAYS = 7


def _create_visitor_token(visitor_id: int) -> str:
    expire = datetime.now(timezone.utc) + timedelta(days=_VISITOR_TOKEN_EXPIRE_DAYS)
    return jwt.encode(
        {"sub": "visitor", "visitor_id": visitor_id, "exp": expire},
        _SECRET_KEY,
        algorithm=_ALGORITHM,
    )


async def require_visitor(
    creds: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
) -> int:
    """Dependency that validates visitor JWT and returns the visitor's user ID."""
    if creds is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
    try:
        payload = jwt.decode(creds.credentials, _SECRET_KEY, algorithms=[_ALGORITHM])
        if payload.get("sub") != "visitor":
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
        visitor_id = payload.get("visitor_id")
        if not visitor_id:
            raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
        return int(visitor_id)
    except JWTError:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")


# ---------------------------------------------------------------------------
# Auth routes (no auth required)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/login", response_model=TokenResponse)
async def login(req: LoginRequest) -> TokenResponse:
    stored_hash: str = _runtime.get("admin_password_hash", "")
    username: str = _runtime.get("admin_username", "admin")

    if req.username != username or not _pwd_ctx.verify(req.password, stored_hash):
        raise HTTPException(status_code=401, detail="Invalid credentials")

    return TokenResponse(access_token=_create_token())


# ---------------------------------------------------------------------------
# Site login (proxy to szhdy.com — saves cookie to DB config)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/site_login", dependencies=[Depends(require_auth)])
async def site_login(req: SiteLoginRequest) -> JSONResponse:
    """Log into szhdy.com with username + API key and store the JWT token in config."""
    try:
        async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
            r = await client.post(
                "https://www.szhdy.com/zjmf_api_login",
                json={"username": req.username, "password": req.api_key},
                headers={"Content-Type": "application/json"},
            )
            body: dict = {}
            try:
                body = r.json()
            except Exception:
                pass

            # JWT is in response.data.jwt (preferred) or response.jwt
            body_data = body.get("data")
            jwt_token: str = (
                body_data.get("jwt", "") if isinstance(body_data, dict)
                else body.get("jwt", "")
            )

            if r.status_code == 200 and jwt_token:
                await database.update_config(login_token=jwt_token)
                return JSONResponse({"status": "ok", "message": "登录成功，JWT 已保存"})
            else:
                msg = body.get("msg") or body.get("message") or f"HTTP {r.status_code}"
                return JSONResponse(
                    {"status": "error", "message": f"登录失败：{msg}"},
                    status_code=400,
                )
    except Exception as e:
        raise HTTPException(status_code=502, detail=str(e))


# ---------------------------------------------------------------------------
# Site accounts management
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/site_accounts", dependencies=[Depends(require_auth)])
async def list_site_accounts() -> JSONResponse:
    accounts = await database.get_site_accounts()
    return JSONResponse(accounts)


@app.post(f"{BASE_PATH}/api/site_accounts", dependencies=[Depends(require_auth)])
async def create_site_account(req: SiteAccountCreate) -> JSONResponse:
    """Login to szhdy.com and save the account with its JWT token."""
    try:
        async with httpx.AsyncClient(timeout=15, follow_redirects=True) as client:
            r = await client.post(
                "https://www.szhdy.com/zjmf_api_login",
                json={"username": req.username, "password": req.api_key},
                headers={"Content-Type": "application/json"},
            )
            body: dict = {}
            try:
                body = r.json()
            except Exception:
                pass

            body_data = body.get("data")
            jwt_token: str = (
                body_data.get("jwt", "") if isinstance(body_data, dict)
                else body.get("jwt", "")
            )

            if r.status_code == 200 and jwt_token:
                label = req.label or req.username
                account_id = await database.add_site_account(label, req.username, req.api_key, jwt_token)
                return JSONResponse({"status": "ok", "id": account_id, "message": "账号已保存"})
            else:
                msg = body.get("msg") or body.get("message") or f"HTTP {r.status_code}"
                return JSONResponse(
                    {"status": "error", "message": f"登录失败：{msg}"},
                    status_code=400,
                )
    except Exception as e:
        raise HTTPException(status_code=502, detail=str(e))


@app.delete(f"{BASE_PATH}/api/site_accounts/{{account_id}}", dependencies=[Depends(require_auth)])
async def remove_site_account(account_id: int) -> JSONResponse:
    await database.delete_site_account(account_id)
    return JSONResponse({"status": "ok"})


@app.post(f"{BASE_PATH}/api/site_accounts/{{account_id}}/activate", dependencies=[Depends(require_auth)])
async def activate_site_account(account_id: int) -> JSONResponse:
    await database.set_active_site_account(account_id)
    return JSONResponse({"status": "ok", "message": "已切换为当前账号"})


# ---------------------------------------------------------------------------
# Config routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/config", dependencies=[Depends(require_auth)])
async def get_config() -> JSONResponse:
    cfg = await database.get_config()
    # Don't expose full token/cookie to frontend
    cfg_out = {k: v for k, v in cfg.items() if k not in ("login_cookie", "login_token")}
    cfg_out["has_cookie"] = bool(cfg.get("login_cookie"))
    cfg_out["has_token"] = bool(cfg.get("login_token"))
    return JSONResponse(cfg_out)


@app.put(f"{BASE_PATH}/api/config", dependencies=[Depends(require_auth)])
async def update_config(body: ConfigUpdate) -> JSONResponse:
    update: dict[str, Any] = {}
    provided = getattr(body, "model_fields_set", set()) or getattr(body, "__fields_set__", set())
    if "start_pid" in provided and body.start_pid is not None:
        update["start_pid"] = body.start_pid
    if "end_pid" in provided and body.end_pid is not None:
        update["end_pid"] = body.end_pid
    if "exec_start_pid" in provided:
        update["exec_start_pid"] = body.exec_start_pid
    if "interval_ms" in provided and body.interval_ms is not None:
        update["interval_ms"] = max(500, body.interval_ms)
    if "loop_enabled" in provided and body.loop_enabled is not None:
        update["loop_enabled"] = body.loop_enabled
    if "login_cookie" in provided:
        update["login_cookie"] = body.login_cookie
    if "notify_channels" in provided and body.notify_channels is not None:
        update["notify_channels"] = body.notify_channels
    if "notify_price_min" in provided:
        update["notify_price_min"] = body.notify_price_min
    if "notify_price_max" in provided:
        update["notify_price_max"] = body.notify_price_max
    if "notify_monthly_price_min" in provided:
        update["notify_monthly_price_min"] = body.notify_monthly_price_min
    if "notify_monthly_price_max" in provided:
        update["notify_monthly_price_max"] = body.notify_monthly_price_max
    await database.update_config(**update)
    return JSONResponse({"status": "ok"})


# ---------------------------------------------------------------------------
# Crawler routes
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/crawler/start", dependencies=[Depends(require_auth)])
async def start_crawler() -> JSONResponse:
    started = crawler.start_crawler()
    return JSONResponse({"started": started})


@app.post(f"{BASE_PATH}/api/crawler/stop", dependencies=[Depends(require_auth)])
async def stop_crawler() -> JSONResponse:
    await crawler.stop_crawler()
    return JSONResponse({"stopped": True})


@app.post(f"{BASE_PATH}/api/notify/toggle_pause", dependencies=[Depends(require_auth)])
async def toggle_notify_pause() -> JSONResponse:
    """Toggle notification pause for the current crawl round.
    Auto-resets to unpaused at the start of the next round."""
    paused = crawler.toggle_notify_pause()
    return JSONResponse({"notify_paused": paused})


@app.post(f"{BASE_PATH}/api/notify/toggle_filter_sold_out", dependencies=[Depends(require_auth)])
async def toggle_filter_sold_out() -> JSONResponse:
    """Toggle sold-out notification filter. When enabled, out_of_stock notifications are suppressed."""
    filter_sold_out = crawler.toggle_filter_sold_out()
    return JSONResponse({"filter_sold_out": filter_sold_out})


@app.get(f"{BASE_PATH}/api/crawler/status", dependencies=[Depends(require_auth)])
async def crawler_status() -> CrawlerStatus:
    status_obj = crawler.get_status()
    cfg = await database.get_config()
    status_obj.start_pid = cfg.get("start_pid")
    status_obj.end_pid = cfg.get("end_pid")
    status_obj.exec_start_pid = cfg.get("exec_start_pid")
    status_obj.loop_enabled = cfg.get("loop_enabled", False)
    status_obj.notify_paused = crawler.state.notify_paused
    status_obj.filter_sold_out = crawler.state.filter_sold_out
    return status_obj


# ---------------------------------------------------------------------------
# Product routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/products", dependencies=[Depends(require_auth)])
async def list_products(
    page: int = 1,
    page_size: int = 20,
    name: Optional[str] = None,
    stock_status: Optional[str] = None,
    billingcycle: Optional[str] = None,
    price_min: Optional[float] = None,
    price_max: Optional[float] = None,
    sort_price: Optional[str] = None,
) -> JSONResponse:
    page_size = min(max(page_size, 1), 200)
    offset = (page - 1) * page_size
    sort_price = sort_price if sort_price in ("asc", "desc") else None
    products = await database.get_products(
        limit=page_size,
        offset=offset,
        name=name,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
        sort_price=sort_price,
    )
    total = await database.count_products(
        name=name,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
    )
    return JSONResponse({"total": total, "page": page, "page_size": page_size, "items": products})


@app.get(f"{BASE_PATH}/api/products/filter_options", dependencies=[Depends(require_auth)])
async def product_filter_options() -> JSONResponse:
    opts = await database.get_product_filter_options()
    return JSONResponse(opts)


@app.get(f"{BASE_PATH}/api/products/{{pid}}/history", dependencies=[Depends(require_auth)])
async def product_history(pid: int, page: int = 1, page_size: int = 50) -> PaginatedChanges:
    total, items = await database.get_changes(pid=pid, page=page, page_size=page_size)
    return PaginatedChanges(
        total=total,
        page=page,
        page_size=page_size,
        items=[ChangeLog(**i) for i in items],
    )


# ---------------------------------------------------------------------------
# Changes route
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/changes", dependencies=[Depends(require_auth)])
async def list_changes(page: int = 1, page_size: int = 50) -> PaginatedChanges:
    total, items = await database.get_changes(page=page, page_size=page_size)
    return PaginatedChanges(
        total=total,
        page=page,
        page_size=page_size,
        items=[ChangeLog(**i) for i in items],
    )


@app.delete(f"{BASE_PATH}/api/changes", dependencies=[Depends(require_auth)])
async def delete_changes() -> JSONResponse:
    await database.clear_changes()
    return JSONResponse({"status": "ok"})


# ---------------------------------------------------------------------------
# Notify test route
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/notify/test", dependencies=[Depends(require_auth)])
async def test_notify(req: NotifyTestRequest) -> JSONResponse:
    success = await notifier.send_channel(
        req.channel, req.config, title="HDY Monitor 测试通知", body="通知渠道配置成功！"
    )
    return JSONResponse({"success": success})


# ---------------------------------------------------------------------------
# Backup & Restore routes
# ---------------------------------------------------------------------------

_SQLITE_MAGIC = b"SQLite format 3\x00"


@app.get(f"{BASE_PATH}/api/backup", dependencies=[Depends(require_auth)])
async def download_backup() -> FileResponse:
    """Download the full SQLite database as a backup file."""
    if not os.path.exists(database.DB_PATH):
        raise HTTPException(status_code=404, detail="数据库文件不存在")
    return FileResponse(
        database.DB_PATH,
        media_type="application/octet-stream",
        filename="hdy_backup.db",
    )


@app.post(f"{BASE_PATH}/api/restore", dependencies=[Depends(require_auth)])
async def restore_backup(file: UploadFile = File(...)) -> JSONResponse:
    """Upload a previously downloaded backup and replace the current database."""
    content = await file.read()
    if not content.startswith(_SQLITE_MAGIC):
        raise HTTPException(status_code=400, detail="不是有效的 SQLite 数据库文件")

    # Stop the crawler before replacing the DB
    await crawler.stop_crawler()

    db_dir = os.path.dirname(os.path.abspath(database.DB_PATH))
    try:
        with tempfile.NamedTemporaryFile(dir=db_dir, delete=False, suffix=".tmp") as tmp:
            tmp.write(content)
            tmp_path = tmp.name
        os.replace(tmp_path, database.DB_PATH)
        # Re-run migrations to ensure schema is up to date
        await database.init_db()
    except Exception as e:
        try:
            os.remove(tmp_path)
        except Exception:
            pass
        raise HTTPException(status_code=500, detail=str(e))

    return JSONResponse({"status": "ok", "message": "数据库已恢复，请刷新页面"})


# ---------------------------------------------------------------------------
# Admin — visitor user management routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/visitors", dependencies=[Depends(require_auth)])
async def list_visitors() -> JSONResponse:
    visitors = await database.get_visitor_users()
    return JSONResponse(visitors)


@app.post(f"{BASE_PATH}/api/visitors", dependencies=[Depends(require_auth)])
async def create_visitor(req: VisitorUserCreate) -> JSONResponse:
    username = req.username.strip()
    if not username or not req.password:
        raise HTTPException(status_code=400, detail="账号和密码不能为空")
    existing = await database.get_visitor_by_username(username)
    if existing:
        raise HTTPException(status_code=409, detail="该账号已存在")
    password_hash = _pwd_ctx.hash(req.password)
    visitor_id = await database.create_visitor_user(username, password_hash, req.label)
    return JSONResponse({"status": "ok", "id": visitor_id, "message": "访客账号已创建"})


@app.delete(f"{BASE_PATH}/api/visitors/{{visitor_id}}", dependencies=[Depends(require_auth)])
async def delete_visitor(visitor_id: int) -> JSONResponse:
    await database.delete_visitor_user(visitor_id)
    return JSONResponse({"status": "ok"})


@app.put(f"{BASE_PATH}/api/visitors/{{visitor_id}}/password", dependencies=[Depends(require_auth)])
async def reset_visitor_password(visitor_id: int, req: VisitorPasswordUpdate) -> JSONResponse:
    if not req.password:
        raise HTTPException(status_code=400, detail="密码不能为空")
    password_hash = _pwd_ctx.hash(req.password)
    await database.update_visitor_password(visitor_id, password_hash)
    return JSONResponse({"status": "ok", "message": "密码已重置"})


# ---------------------------------------------------------------------------
# Visitor — public routes (visitor JWT required)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/visitor/login", response_model=TokenResponse)
async def visitor_login(req: VisitorLoginRequest) -> TokenResponse:
    visitor = await database.get_visitor_by_username(req.username.strip())
    if not visitor or not visitor.get("is_active"):
        raise HTTPException(status_code=401, detail="账号或密码错误")
    if not _pwd_ctx.verify(req.password, visitor.get("password_hash", "")):
        raise HTTPException(status_code=401, detail="账号或密码错误")
    token = _create_visitor_token(visitor["id"])
    return TokenResponse(access_token=token)


@app.get(f"{BASE_PATH}/api/visitor/me")
async def visitor_me(visitor_id: int = Depends(require_visitor)) -> JSONResponse:
    visitor = await database.get_visitor_by_id(visitor_id)
    if not visitor:
        raise HTTPException(status_code=404, detail="访客账号不存在")
    return JSONResponse(visitor)


@app.put(f"{BASE_PATH}/api/visitor/me/notify")
async def visitor_update_notify(
    req: VisitorNotifyUpdate,
    visitor_id: int = Depends(require_visitor),
) -> JSONResponse:
    await database.update_visitor_notify(
        visitor_id,
        req.notify_channels,
        req.notify_price_min,
        req.notify_price_max,
        req.notify_monthly_price_min,
        req.notify_monthly_price_max,
    )
    return JSONResponse({"status": "ok"})


@app.post(f"{BASE_PATH}/api/visitor/notify/test")
async def visitor_test_notify(
    req: NotifyTestRequest,
    visitor_id: int = Depends(require_visitor),
) -> JSONResponse:
    success = await notifier.send_channel(
        req.channel, req.config, title="HDY Monitor 测试通知", body="通知渠道配置成功！"
    )
    return JSONResponse({"success": success})


@app.get(f"{BASE_PATH}/api/visitor/products")
async def visitor_list_products(
    page: int = 1,
    page_size: int = 20,
    name: Optional[str] = None,
    stock_status: Optional[str] = None,
    billingcycle: Optional[str] = None,
    price_min: Optional[float] = None,
    price_max: Optional[float] = None,
    sort_price: Optional[str] = None,
    visitor_id: int = Depends(require_visitor),
) -> JSONResponse:
    page_size = min(max(page_size, 1), 200)
    offset = (page - 1) * page_size
    sort_price = sort_price if sort_price in ("asc", "desc") else None
    products = await database.get_products(
        limit=page_size,
        offset=offset,
        name=name,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
        sort_price=sort_price,
    )
    total = await database.count_products(
        name=name,
        stock_status=stock_status,
        billingcycle=billingcycle,
        price_min=price_min,
        price_max=price_max,
    )
    return JSONResponse({"total": total, "page": page, "page_size": page_size, "items": products})


@app.get(f"{BASE_PATH}/api/visitor/products/filter_options")
async def visitor_product_filter_options(
    visitor_id: int = Depends(require_visitor),
) -> JSONResponse:
    opts = await database.get_product_filter_options()
    return JSONResponse(opts)


# ---------------------------------------------------------------------------
# Agent — token authentication helper
# ---------------------------------------------------------------------------

async def _require_agent(
    creds: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
) -> dict[str, Any]:
    """Validate the agent bearer token and return the agent record."""
    if creds is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Unauthorized")
    agent = await database.get_agent_by_token(creds.credentials)
    if agent is None:
        raise HTTPException(status_code=status.HTTP_401_UNAUTHORIZED, detail="Invalid agent token")
    return agent


# ---------------------------------------------------------------------------
# Admin — agent management routes
# ---------------------------------------------------------------------------

@app.get(f"{BASE_PATH}/api/agents", dependencies=[Depends(require_auth)])
async def list_agents() -> JSONResponse:
    agents = await database.get_agents()
    # Don't expose raw token to frontend; show only first/last 4 chars
    for a in agents:
        tok = a.get("token", "")
        if len(tok) > 8:
            a["token_hint"] = tok[:4] + "…" + tok[-4:]
        else:
            a["token_hint"] = "****"
        del a["token"]
    return JSONResponse(agents)


@app.post(f"{BASE_PATH}/api/agents", dependencies=[Depends(require_auth)])
async def create_agent(req: AgentCreate, request: Request) -> JSONResponse:
    token = secrets.token_urlsafe(32)
    agent_id = await database.create_agent(req.name.strip() or "未命名客户端", token)
    # Auto-detect server URL if not provided
    if req.server_url:
        server_url = req.server_url.rstrip("/")
    else:
        scheme = request.url.scheme
        host = request.headers.get("host") or request.url.netloc
        server_url = f"{scheme}://{host}{BASE_PATH}"
    install_cmd = f'bash <(curl -fsSL "{server_url}/api/agent/setup/{token}")'
    return JSONResponse({
        "status": "ok",
        "id": agent_id,
        "install_cmd": install_cmd,
        "message": "客户端已创建，请复制安装命令在目标服务器上执行",
    })


@app.delete(f"{BASE_PATH}/api/agents/{{agent_id}}", dependencies=[Depends(require_auth)])
async def delete_agent(agent_id: int) -> JSONResponse:
    await database.delete_agent(agent_id)
    return JSONResponse({"status": "ok"})


@app.put(f"{BASE_PATH}/api/agents/{{agent_id}}/task", dependencies=[Depends(require_auth)])
async def assign_agent_task(agent_id: int, req: AgentTaskAssign) -> JSONResponse:
    agent = await database.get_agent_by_id(agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail="客户端不存在")
    # Include current active login token so the agent can scan
    cfg = await database.get_config()
    login_token = cfg.get("login_token") or cfg.get("login_cookie") or ""
    task = {
        "type": "scan",
        "start_pid": req.start_pid,
        "end_pid": req.end_pid,
        "interval_ms": max(500, req.interval_ms),
        "loop_enabled": req.loop_enabled,
        "login_token": login_token,
    }
    await database.update_agent_task(agent_id, task)
    return JSONResponse({"status": "ok", "message": "扫描任务已下发"})


@app.delete(f"{BASE_PATH}/api/agents/{{agent_id}}/task", dependencies=[Depends(require_auth)])
async def clear_agent_task(agent_id: int) -> JSONResponse:
    agent = await database.get_agent_by_id(agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail="客户端不存在")
    await database.update_agent_task(agent_id, {"type": "idle"})
    return JSONResponse({"status": "ok", "message": "任务已清除"})


@app.post(f"{BASE_PATH}/api/agents/{{agent_id}}/upgrade", dependencies=[Depends(require_auth)])
async def push_agent_upgrade(agent_id: int) -> JSONResponse:
    agent = await database.get_agent_by_id(agent_id)
    if not agent:
        raise HTTPException(status_code=404, detail="客户端不存在")
    await database.update_agent_task(agent_id, {"type": "upgrade"})
    return JSONResponse({"status": "ok", "message": "升级命令已下发，客户端将在下次心跳时升级"})


@app.get(f"{BASE_PATH}/api/agents/{{agent_id}}/reports", dependencies=[Depends(require_auth)])
async def get_agent_reports(agent_id: int, limit: int = 50) -> JSONResponse:
    limit = min(max(limit, 1), 200)
    reports = await database.get_agent_reports(agent_id, limit)
    return JSONResponse(reports)


# ---------------------------------------------------------------------------
# Public — agent setup script & agent script download
# ---------------------------------------------------------------------------

_AGENT_SCRIPT_PATH = Path(__file__).parent / "agent.py"


@app.get(f"{BASE_PATH}/api/agent/setup/{{token}}", include_in_schema=False)
async def agent_setup_script(token: str, request: Request) -> PlainTextResponse:
    """Return a bash install script for the agent with the given token embedded."""
    agent = await database.get_agent_by_token(token)
    if not agent:
        raise HTTPException(status_code=404, detail="Invalid token")
    scheme = request.url.scheme
    host = request.headers.get("host") or request.url.netloc
    server_url = f"{scheme}://{host}{BASE_PATH}"
    script = _build_agent_setup_script(server_url, token)
    return PlainTextResponse(script, media_type="text/x-shellscript")


@app.get(f"{BASE_PATH}/api/agent/script", include_in_schema=False)
async def get_agent_script(
    creds: Optional[HTTPAuthorizationCredentials] = Depends(_bearer),
) -> PlainTextResponse:
    """Return the agent.py script — requires valid agent token."""
    if creds is None:
        raise HTTPException(status_code=401, detail="Unauthorized")
    agent = await database.get_agent_by_token(creds.credentials)
    if not agent:
        raise HTTPException(status_code=401, detail="Invalid agent token")
    if not _AGENT_SCRIPT_PATH.exists():
        raise HTTPException(status_code=404, detail="agent.py not found on server")
    return PlainTextResponse(_AGENT_SCRIPT_PATH.read_text(encoding="utf-8"), media_type="text/x-python")


def _build_agent_setup_script(server_url: str, token: str) -> str:
    return f"""#!/usr/bin/env bash
# HDY Agent — One-Click Installer
# Generated by HDY Monitor
set -euo pipefail

RED='\\033[0;31m'; GREEN='\\033[0;32m'; CYAN='\\033[0;36m'; NC='\\033[0m'
info()    {{ echo -e "${{CYAN}}[INFO]${{NC}}  $*"; }}
success() {{ echo -e "${{GREEN}}[OK]${{NC}}    $*"; }}
die()     {{ echo -e "${{RED}}[ERROR]${{NC}} $*"; exit 1; }}

SERVER_URL="{server_url}"
AGENT_TOKEN="{token}"
INSTALL_DIR="/opt/hdy-agent"
SERVICE_NAME="hdy-agent"
SERVICE_FILE="/etc/systemd/system/${{SERVICE_NAME}}.service"

[[ $EUID -ne 0 ]] && die "请使用 sudo 或 root 运行此脚本"

info "安装系统依赖..."
apt-get update -qq 2>/dev/null || true
apt-get install -y -qq python3 python3-pip python3-venv curl 2>/dev/null || true

info "创建安装目录 ${{INSTALL_DIR}}..."
mkdir -p "${{INSTALL_DIR}}"

info "下载 agent 脚本..."
curl -fsSL "${{SERVER_URL}}/api/agent/script" \\
  -H "Authorization: Bearer ${{AGENT_TOKEN}}" \\
  -o "${{INSTALL_DIR}}/agent.py"

info "写入配置文件..."
cat > "${{INSTALL_DIR}}/config.json" <<JSON
{{
  "server_url": "${{SERVER_URL}}",
  "token": "${{AGENT_TOKEN}}"
}}
JSON
chmod 600 "${{INSTALL_DIR}}/config.json"

info "创建 Python 虚拟环境..."
python3 -m venv "${{INSTALL_DIR}}/venv"
"${{INSTALL_DIR}}/venv/bin/pip" install -q --upgrade pip
"${{INSTALL_DIR}}/venv/bin/pip" install -q httpx

info "创建 systemd 服务..."
cat > "${{SERVICE_FILE}}" <<SVC
[Unit]
Description=HDY Agent
After=network.target

[Service]
Type=simple
User=root
WorkingDirectory=${{INSTALL_DIR}}
ExecStart=${{INSTALL_DIR}}/venv/bin/python ${{INSTALL_DIR}}/agent.py
Restart=always
RestartSec=10
Environment=HDY_AGENT_CONFIG=${{INSTALL_DIR}}/config.json

[Install]
WantedBy=multi-user.target
SVC

systemctl daemon-reload
systemctl enable "${{SERVICE_NAME}}" --quiet
systemctl restart "${{SERVICE_NAME}}"
success "HDY Agent 已安装并启动！"
echo ""
echo "  管理命令:"
echo "    systemctl status ${{SERVICE_NAME}}   # 查看状态"
echo "    journalctl -u ${{SERVICE_NAME}} -f   # 查看日志"
echo "    systemctl stop ${{SERVICE_NAME}}     # 停止"
echo ""
"""


# ---------------------------------------------------------------------------
# Client — agent heartbeat & report (authenticated by agent token)
# ---------------------------------------------------------------------------

@app.post(f"{BASE_PATH}/api/agent/heartbeat")
async def agent_heartbeat(
    req: AgentHeartbeatRequest,
    request: Request,
    agent: dict[str, Any] = Depends(_require_agent),
) -> JSONResponse:
    """Agent calls this periodically; server returns the current command/task."""
    ip_addr = request.headers.get("x-forwarded-for", request.client.host if request.client else None)
    if ip_addr:
        ip_addr = ip_addr.split(",")[0].strip()
    await database.update_agent_heartbeat(
        agent["id"],
        req.status or "online",
        req.version,
        ip_addr,
    )
    task = agent.get("task") or {"type": "idle"}
    task_type = task.get("type", "idle")

    # If it's a scan task, refresh the login token before returning
    if task_type == "scan":
        cfg = await database.get_config()
        task = dict(task)
        task["login_token"] = cfg.get("login_token") or cfg.get("login_cookie") or ""

    return JSONResponse({"command": task_type, "task": task})


@app.post(f"{BASE_PATH}/api/agent/report")
async def agent_report(
    req: AgentReportRequest,
    agent: dict[str, Any] = Depends(_require_agent),
) -> JSONResponse:
    """Agent reports a detected product change."""
    await database.add_agent_report(
        agent["id"],
        req.pid,
        req.name,
        req.price,
        req.stock_status,
        req.changed_fields,
    )

    # Send notification using global channels
    if req.changed_fields:
        cfg = await database.get_config()
        notify_channels: dict[str, Any] = cfg.get("notify_channels", {})
        agent_name = agent.get("name") or "未知客户端"
        stock_map = {"in_stock": "有货", "out_of_stock": "无货", "unknown": "未知"}
        stock_zh = stock_map.get(req.stock_status or "", req.stock_status or "未知")
        fields_zh = "、".join(req.changed_fields)
        title = f"[客户端] PID {req.pid} 变化"
        body = (
            f"来源: {agent_name}\n"
            f"PID: {req.pid}\n"
            f"名称: {req.name or '—'}\n"
            f"价格: {req.price or '—'}\n"
            f"库存: {stock_zh}\n"
            f"变化字段: {fields_zh}"
        )
        for ch_key, ch_cfg in notify_channels.items():
            if not (isinstance(ch_cfg, dict) and ch_cfg.get("enabled")):
                continue
            try:
                await notifier.send_channel(ch_key, ch_cfg, title=title, body=body)
            except Exception:
                pass

    return JSONResponse({"status": "ok"})



_ASSETS_DIR = _STATIC_DIR / "assets"

if _STATIC_DIR.exists():
    # Serve static assets (only mount if the assets subdirectory exists)
    if _ASSETS_DIR.exists():
        app.mount(f"{BASE_PATH}/assets", StaticFiles(directory=str(_ASSETS_DIR)), name="assets")

    @app.get(f"{BASE_PATH}/", include_in_schema=False)
    @app.get(f"{BASE_PATH}", include_in_schema=False)
    async def serve_index() -> FileResponse:
        return FileResponse(str(_STATIC_DIR / "index.html"))

    @app.get(f"{BASE_PATH}/visitor", include_in_schema=False)
    @app.get(f"{BASE_PATH}/visitor/", include_in_schema=False)
    async def serve_visitor_page() -> FileResponse:
        vf = _STATIC_DIR / "visitor.html"
        if not vf.exists():
            raise HTTPException(status_code=404)
        return FileResponse(str(vf))

    # Catch-all for SPA routing
    @app.get(f"{BASE_PATH}/{{full_path:path}}", include_in_schema=False)
    async def spa_fallback(full_path: str) -> FileResponse:
        if full_path.startswith("api/"):
            raise HTTPException(status_code=404)
        return FileResponse(str(_STATIC_DIR / "index.html"))
